#
server:
  port: 7000
#
logging:
  config: classpath:logback.xml
#####################
#（★）Spring
#####################
spring:
  application:
    name: study-springboot-shiro-token
  main:
    web-application-type: servlet
    banner-mode: 'off'
  redis:
    host: 114.67.102.8
    port: 7379
    database: 0
    timeout: 60000
  profiles:
    active: @env@